package com.sinosoft.bms.entity;
// Generated 2009-5-19 11:36:48 by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;


/**
 * BmsAlertId generated by hbm2java
 */

public class BmsAlertId  implements java.io.Serializable {


    // Fields    

     private Integer itemId;
     private Integer bgSchId;
     private BigDecimal normalPercent;
     private BigDecimal alertPercent;
     private BigDecimal seriousPercent;


    // Constructors

    /** default constructor */
    public BmsAlertId() {
    }

    
    /** full constructor */
    public BmsAlertId(Integer itemId, Integer bgSchId, BigDecimal normalPercent, BigDecimal alertPercent, BigDecimal seriousPercent) {
        this.itemId = itemId;
        this.bgSchId = bgSchId;
        this.normalPercent = normalPercent;
        this.alertPercent = alertPercent;
        this.seriousPercent = seriousPercent;
    }
    

   
    // Property accessors

    public Integer getItemId() {
        return this.itemId;
    }
    
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    public Integer getBgSchId() {
        return this.bgSchId;
    }
    
    public void setBgSchId(Integer bgSchId) {
        this.bgSchId = bgSchId;
    }

    public BigDecimal getNormalPercent() {
        return this.normalPercent;
    }
    
    public void setNormalPercent(BigDecimal normalPercent) {
        this.normalPercent = normalPercent;
    }

    public BigDecimal getAlertPercent() {
        return this.alertPercent;
    }
    
    public void setAlertPercent(BigDecimal alertPercent) {
        this.alertPercent = alertPercent;
    }

    public BigDecimal getSeriousPercent() {
        return this.seriousPercent;
    }
    
    public void setSeriousPercent(BigDecimal seriousPercent) {
        this.seriousPercent = seriousPercent;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BmsAlertId) ) return false;
		 BmsAlertId castOther = ( BmsAlertId ) other; 
         
		 return ( (this.getItemId()==castOther.getItemId()) || ( this.getItemId()!=null && castOther.getItemId()!=null && this.getItemId().equals(castOther.getItemId()) ) )
 && ( (this.getBgSchId()==castOther.getBgSchId()) || ( this.getBgSchId()!=null && castOther.getBgSchId()!=null && this.getBgSchId().equals(castOther.getBgSchId()) ) )
 && ( (this.getNormalPercent()==castOther.getNormalPercent()) || ( this.getNormalPercent()!=null && castOther.getNormalPercent()!=null && this.getNormalPercent().equals(castOther.getNormalPercent()) ) )
 && ( (this.getAlertPercent()==castOther.getAlertPercent()) || ( this.getAlertPercent()!=null && castOther.getAlertPercent()!=null && this.getAlertPercent().equals(castOther.getAlertPercent()) ) )
 && ( (this.getSeriousPercent()==castOther.getSeriousPercent()) || ( this.getSeriousPercent()!=null && castOther.getSeriousPercent()!=null && this.getSeriousPercent().equals(castOther.getSeriousPercent()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getItemId() == null ? 0 : this.getItemId().hashCode() );
         result = 37 * result + ( getBgSchId() == null ? 0 : this.getBgSchId().hashCode() );
         result = 37 * result + ( getNormalPercent() == null ? 0 : this.getNormalPercent().hashCode() );
         result = 37 * result + ( getAlertPercent() == null ? 0 : this.getAlertPercent().hashCode() );
         result = 37 * result + ( getSeriousPercent() == null ? 0 : this.getSeriousPercent().hashCode() );
         return result;
   }   





}
