package com.sinosoft.bms.entity;
// Generated 2009-5-19 11:36:48 by Hibernate Tools 3.1.0.beta4



/**
 * BmsAttachType generated by hbm2java
 */

public class BmsAttachType  implements java.io.Serializable {


    // Fields    

     private BmsAttachTypeId id;


    // Constructors

    /** default constructor */
    public BmsAttachType() {
    }

    
    /** full constructor */
    public BmsAttachType(BmsAttachTypeId id) {
        this.id = id;
    }
    

   
    // Property accessors

    public BmsAttachTypeId getId() {
        return this.id;
    }
    
    public void setId(BmsAttachTypeId id) {
        this.id = id;
    }
   








}
