package com.sinosoft.bms.entity;
// Generated 2009-5-19 11:36:48 by Hibernate Tools 3.1.0.beta4



/**
 * BmsAttachTypeId generated by hbm2java
 */

public class BmsAttachTypeId  implements java.io.Serializable {


    // Fields    

     private String extName;
     private String typeName;
     private String picPath;


    // Constructors

    /** default constructor */
    public BmsAttachTypeId() {
    }

    
    /** full constructor */
    public BmsAttachTypeId(String extName, String typeName, String picPath) {
        this.extName = extName;
        this.typeName = typeName;
        this.picPath = picPath;
    }
    

   
    // Property accessors

    public String getExtName() {
        return this.extName;
    }
    
    public void setExtName(String extName) {
        this.extName = extName;
    }

    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    public String getPicPath() {
        return this.picPath;
    }
    
    public void setPicPath(String picPath) {
        this.picPath = picPath;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BmsAttachTypeId) ) return false;
		 BmsAttachTypeId castOther = ( BmsAttachTypeId ) other; 
         
		 return ( (this.getExtName()==castOther.getExtName()) || ( this.getExtName()!=null && castOther.getExtName()!=null && this.getExtName().equals(castOther.getExtName()) ) )
 && ( (this.getTypeName()==castOther.getTypeName()) || ( this.getTypeName()!=null && castOther.getTypeName()!=null && this.getTypeName().equals(castOther.getTypeName()) ) )
 && ( (this.getPicPath()==castOther.getPicPath()) || ( this.getPicPath()!=null && castOther.getPicPath()!=null && this.getPicPath().equals(castOther.getPicPath()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getExtName() == null ? 0 : this.getExtName().hashCode() );
         result = 37 * result + ( getTypeName() == null ? 0 : this.getTypeName().hashCode() );
         result = 37 * result + ( getPicPath() == null ? 0 : this.getPicPath().hashCode() );
         return result;
   }   





}
