package com.sinosoft.bms.entity;
// Generated 2009-5-19 11:36:48 by Hibernate Tools 3.1.0.beta4



/**
 * BmsControlId generated by hbm2java
 */

public class BmsControlId  implements java.io.Serializable {


    // Fields    

     private Integer itemId;
     private Integer bgSchId;
     private Character controlFlag;


    // Constructors

    /** default constructor */
    public BmsControlId() {
    }

    
    /** full constructor */
    public BmsControlId(Integer itemId, Integer bgSchId, Character controlFlag) {
        this.itemId = itemId;
        this.bgSchId = bgSchId;
        this.controlFlag = controlFlag;
    }
    

   
    // Property accessors

    public Integer getItemId() {
        return this.itemId;
    }
    
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    public Integer getBgSchId() {
        return this.bgSchId;
    }
    
    public void setBgSchId(Integer bgSchId) {
        this.bgSchId = bgSchId;
    }

    public Character getControlFlag() {
        return this.controlFlag;
    }
    
    public void setControlFlag(Character controlFlag) {
        this.controlFlag = controlFlag;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BmsControlId) ) return false;
		 BmsControlId castOther = ( BmsControlId ) other; 
         
		 return ( (this.getItemId()==castOther.getItemId()) || ( this.getItemId()!=null && castOther.getItemId()!=null && this.getItemId().equals(castOther.getItemId()) ) )
 && ( (this.getBgSchId()==castOther.getBgSchId()) || ( this.getBgSchId()!=null && castOther.getBgSchId()!=null && this.getBgSchId().equals(castOther.getBgSchId()) ) )
 && ( (this.getControlFlag()==castOther.getControlFlag()) || ( this.getControlFlag()!=null && castOther.getControlFlag()!=null && this.getControlFlag().equals(castOther.getControlFlag()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getItemId() == null ? 0 : this.getItemId().hashCode() );
         result = 37 * result + ( getBgSchId() == null ? 0 : this.getBgSchId().hashCode() );
         result = 37 * result + ( getControlFlag() == null ? 0 : this.getControlFlag().hashCode() );
         return result;
   }   





}
