package com.sinosoft.bms.entity;
// Generated 2009-5-19 11:36:47 by Hibernate Tools 3.1.0.beta4

import java.util.HashSet;
import java.util.Set;


/**
 * BmsDim generated by hbm2java
 */

public class BmsDim  implements java.io.Serializable {


    // Fields    

     private int dimId;
     private String dimCode;
     private String dimName;
     private Character isSysDefine;
     private String memStruct;
     private Set bmsDimMembers = new HashSet(0);
     private Set bmsTpParamDims = new HashSet(0);
     private Set bmsGsparamDims = new HashSet(0);


    // Constructors

    /** default constructor */
    public BmsDim() {
    }

	/** minimal constructor */
    public BmsDim(int dimId) {
        this.dimId = dimId;
    }
    
    /** full constructor */
    public BmsDim(int dimId, String dimCode, String dimName, Character isSysDefine, String memStruct, Set bmsDimMembers, Set bmsTpParamDims, Set bmsGsparamDims) {
        this.dimId = dimId;
        this.dimCode = dimCode;
        this.dimName = dimName;
        this.isSysDefine = isSysDefine;
        this.memStruct = memStruct;
        this.bmsDimMembers = bmsDimMembers;
        this.bmsTpParamDims = bmsTpParamDims;
        this.bmsGsparamDims = bmsGsparamDims;
    }
    

   
    // Property accessors

    public int getDimId() {
        return this.dimId;
    }
    
    public void setDimId(int dimId) {
        this.dimId = dimId;
    }

    public String getDimCode() {
        return this.dimCode;
    }
    
    public void setDimCode(String dimCode) {
        this.dimCode = dimCode;
    }

    public String getDimName() {
        return this.dimName;
    }
    
    public void setDimName(String dimName) {
        this.dimName = dimName;
    }

    public Character getIsSysDefine() {
        return this.isSysDefine;
    }
    
    public void setIsSysDefine(Character isSysDefine) {
        this.isSysDefine = isSysDefine;
    }

    public String getMemStruct() {
        return this.memStruct;
    }
    
    public void setMemStruct(String memStruct) {
        this.memStruct = memStruct;
    }

    public Set getBmsDimMembers() {
        return this.bmsDimMembers;
    }
    
    public void setBmsDimMembers(Set bmsDimMembers) {
        this.bmsDimMembers = bmsDimMembers;
    }

    public Set getBmsTpParamDims() {
        return this.bmsTpParamDims;
    }
    
    public void setBmsTpParamDims(Set bmsTpParamDims) {
        this.bmsTpParamDims = bmsTpParamDims;
    }

    public Set getBmsGsparamDims() {
        return this.bmsGsparamDims;
    }
    
    public void setBmsGsparamDims(Set bmsGsparamDims) {
        this.bmsGsparamDims = bmsGsparamDims;
    }
   








}
