package com.sinosoft.bms.entity;
// Generated 2009-5-19 11:36:48 by Hibernate Tools 3.1.0.beta4



/**
 * BmsGsrowDimId generated by hbm2java
 */

public class BmsGsrowDimId  implements java.io.Serializable {


    // Fields    

     private Integer sheetId;
     private Integer itemId;


    // Constructors

    /** default constructor */
    public BmsGsrowDimId() {
    }

    
    /** full constructor */
    public BmsGsrowDimId(Integer sheetId, Integer itemId) {
        this.sheetId = sheetId;
        this.itemId = itemId;
    }
    

   
    // Property accessors

    public Integer getSheetId() {
        return this.sheetId;
    }
    
    public void setSheetId(Integer sheetId) {
        this.sheetId = sheetId;
    }

    public Integer getItemId() {
        return this.itemId;
    }
    
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BmsGsrowDimId) ) return false;
		 BmsGsrowDimId castOther = ( BmsGsrowDimId ) other; 
         
		 return ( (this.getSheetId()==castOther.getSheetId()) || ( this.getSheetId()!=null && castOther.getSheetId()!=null && this.getSheetId().equals(castOther.getSheetId()) ) )
 && ( (this.getItemId()==castOther.getItemId()) || ( this.getItemId()!=null && castOther.getItemId()!=null && this.getItemId().equals(castOther.getItemId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSheetId() == null ? 0 : this.getSheetId().hashCode() );
         result = 37 * result + ( getItemId() == null ? 0 : this.getItemId().hashCode() );
         return result;
   }   





}
