package com.sinosoft.bms.entity;
// Generated 2009-5-19 11:36:47 by Hibernate Tools 3.1.0.beta4



/**
 * BmsGsparamDim generated by hbm2java
 */

public class BmsGsparamDim  implements java.io.Serializable {


    // Fields    

     private BmsGsparamDimId id;
     private BmsDim bmsDim;
     private BmsSheet bmsSheet;
     private BmsDimMember bmsDimMember;


    // Constructors

    /** default constructor */
    public BmsGsparamDim() {
    }

	/** minimal constructor */
    public BmsGsparamDim(BmsGsparamDimId id) {
        this.id = id;
    }
    
    /** full constructor */
    public BmsGsparamDim(BmsGsparamDimId id, BmsDim bmsDim, BmsSheet bmsSheet, BmsDimMember bmsDimMember) {
        this.id = id;
        this.bmsDim = bmsDim;
        this.bmsSheet = bmsSheet;
        this.bmsDimMember = bmsDimMember;
    }
    

   
    // Property accessors

    public BmsGsparamDimId getId() {
        return this.id;
    }
    
    public void setId(BmsGsparamDimId id) {
        this.id = id;
    }

    public BmsDim getBmsDim() {
        return this.bmsDim;
    }
    
    public void setBmsDim(BmsDim bmsDim) {
        this.bmsDim = bmsDim;
    }

    public BmsSheet getBmsSheet() {
        return this.bmsSheet;
    }
    
    public void setBmsSheet(BmsSheet bmsSheet) {
        this.bmsSheet = bmsSheet;
    }

    public BmsDimMember getBmsDimMember() {
        return this.bmsDimMember;
    }
    
    public void setBmsDimMember(BmsDimMember bmsDimMember) {
        this.bmsDimMember = bmsDimMember;
    }
   








}
