package com.sinosoft.bms.entity;
// Generated 2009-5-19 11:36:48 by Hibernate Tools 3.1.0.beta4



/**
 * BmsGschildrenId generated by hbm2java
 */

public class BmsGschildrenId  implements java.io.Serializable {


    // Fields    

     private Integer sheetId;
     private Integer childSheetId;


    // Constructors

    /** default constructor */
    public BmsGschildrenId() {
    }

    
    /** full constructor */
    public BmsGschildrenId(Integer sheetId, Integer childSheetId) {
        this.sheetId = sheetId;
        this.childSheetId = childSheetId;
    }
    

   
    // Property accessors

    public Integer getSheetId() {
        return this.sheetId;
    }
    
    public void setSheetId(Integer sheetId) {
        this.sheetId = sheetId;
    }

    public Integer getChildSheetId() {
        return this.childSheetId;
    }
    
    public void setChildSheetId(Integer childSheetId) {
        this.childSheetId = childSheetId;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BmsGschildrenId) ) return false;
		 BmsGschildrenId castOther = ( BmsGschildrenId ) other; 
         
		 return ( (this.getSheetId()==castOther.getSheetId()) || ( this.getSheetId()!=null && castOther.getSheetId()!=null && this.getSheetId().equals(castOther.getSheetId()) ) )
 && ( (this.getChildSheetId()==castOther.getChildSheetId()) || ( this.getChildSheetId()!=null && castOther.getChildSheetId()!=null && this.getChildSheetId().equals(castOther.getChildSheetId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSheetId() == null ? 0 : this.getSheetId().hashCode() );
         result = 37 * result + ( getChildSheetId() == null ? 0 : this.getChildSheetId().hashCode() );
         return result;
   }   





}
