package com.sinosoft.bms.entity;
// Generated 2009-5-19 11:36:48 by Hibernate Tools 3.1.0.beta4



/**
 * BmsGsparamDimId generated by hbm2java
 */

public class BmsGsparamDimId  implements java.io.Serializable {


    // Fields    

     private Integer sheetId;
     private Integer dimId;
     private Integer dimMemId;


    // Constructors

    /** default constructor */
    public BmsGsparamDimId() {
    }

    
    /** full constructor */
    public BmsGsparamDimId(Integer sheetId, Integer dimId, Integer dimMemId) {
        this.sheetId = sheetId;
        this.dimId = dimId;
        this.dimMemId = dimMemId;
    }
    

   
    // Property accessors

    public Integer getSheetId() {
        return this.sheetId;
    }
    
    public void setSheetId(Integer sheetId) {
        this.sheetId = sheetId;
    }

    public Integer getDimId() {
        return this.dimId;
    }
    
    public void setDimId(Integer dimId) {
        this.dimId = dimId;
    }

    public Integer getDimMemId() {
        return this.dimMemId;
    }
    
    public void setDimMemId(Integer dimMemId) {
        this.dimMemId = dimMemId;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BmsGsparamDimId) ) return false;
		 BmsGsparamDimId castOther = ( BmsGsparamDimId ) other; 
         
		 return ( (this.getSheetId()==castOther.getSheetId()) || ( this.getSheetId()!=null && castOther.getSheetId()!=null && this.getSheetId().equals(castOther.getSheetId()) ) )
 && ( (this.getDimId()==castOther.getDimId()) || ( this.getDimId()!=null && castOther.getDimId()!=null && this.getDimId().equals(castOther.getDimId()) ) )
 && ( (this.getDimMemId()==castOther.getDimMemId()) || ( this.getDimMemId()!=null && castOther.getDimMemId()!=null && this.getDimMemId().equals(castOther.getDimMemId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSheetId() == null ? 0 : this.getSheetId().hashCode() );
         result = 37 * result + ( getDimId() == null ? 0 : this.getDimId().hashCode() );
         result = 37 * result + ( getDimMemId() == null ? 0 : this.getDimMemId().hashCode() );
         return result;
   }   





}
