package com.sinosoft.bms.entity;
// Generated 2009-5-19 11:36:47 by Hibernate Tools 3.1.0.beta4



/**
 * BmsId generated by hbm2java
 */

public class BmsId  implements java.io.Serializable {


    // Fields    

     private BmsIdId id;


    // Constructors

    /** default constructor */
    public BmsId() {
    }

    
    /** full constructor */
    public BmsId(BmsIdId id) {
        this.id = id;
    }
    

   
    // Property accessors

    public BmsIdId getId() {
        return this.id;
    }
    
    public void setId(BmsIdId id) {
        this.id = id;
    }
   








}
