package com.sinosoft.bms.entity;
// Generated 2009-5-19 11:36:47 by Hibernate Tools 3.1.0.beta4

import java.util.HashSet;
import java.util.Set;


/**
 * BmsItemCate generated by hbm2java
 */

public class BmsItemCate  implements java.io.Serializable {


    // Fields    

     private int itemCateId;
     private String itemCateCode;
     private String itemCateName;
     private Set bmsItems = new HashSet(0);


    // Constructors

    /** default constructor */
    public BmsItemCate() {
    }

	/** minimal constructor */
    public BmsItemCate(int itemCateId) {
        this.itemCateId = itemCateId;
    }
    
    /** full constructor */
    public BmsItemCate(int itemCateId, String itemCateCode, String itemCateName, Set bmsItems) {
        this.itemCateId = itemCateId;
        this.itemCateCode = itemCateCode;
        this.itemCateName = itemCateName;
        this.bmsItems = bmsItems;
    }
    

   
    // Property accessors

    public int getItemCateId() {
        return this.itemCateId;
    }
    
    public void setItemCateId(int itemCateId) {
        this.itemCateId = itemCateId;
    }

    public String getItemCateCode() {
        return this.itemCateCode;
    }
    
    public void setItemCateCode(String itemCateCode) {
        this.itemCateCode = itemCateCode;
    }

    public String getItemCateName() {
        return this.itemCateName;
    }
    
    public void setItemCateName(String itemCateName) {
        this.itemCateName = itemCateName;
    }

    public Set getBmsItems() {
        return this.bmsItems;
    }
    
    public void setBmsItems(Set bmsItems) {
        this.bmsItems = bmsItems;
    }
   








}
