package com.sinosoft.bms.entity;
// Generated 2009-5-19 11:23:11 by Hibernate Tools 3.1.0.beta4

import java.util.HashSet;
import java.util.Set;


/**
 * BmsItemType generated by hbm2java
 */

public class BmsItemType  implements java.io.Serializable {


    // Fields    

     private int itemTypeId;
     private String itemTypeCode;
     private String itemTypeName;
     private Set bmsItems = new HashSet(0);


    // Constructors

    /** default constructor */
    public BmsItemType() {
    }

	/** minimal constructor */
    public BmsItemType(int itemTypeId) {
        this.itemTypeId = itemTypeId;
    }
    
    /** full constructor */
    public BmsItemType(int itemTypeId, String itemTypeCode, String itemTypeName, Set bmsItems) {
        this.itemTypeId = itemTypeId;
        this.itemTypeCode = itemTypeCode;
        this.itemTypeName = itemTypeName;
        this.bmsItems = bmsItems;
    }
    

   
    // Property accessors

    public int getItemTypeId() {
        return this.itemTypeId;
    }
    
    public void setItemTypeId(int itemTypeId) {
        this.itemTypeId = itemTypeId;
    }

    public String getItemTypeCode() {
        return this.itemTypeCode;
    }
    
    public void setItemTypeCode(String itemTypeCode) {
        this.itemTypeCode = itemTypeCode;
    }

    public String getItemTypeName() {
        return this.itemTypeName;
    }
    
    public void setItemTypeName(String itemTypeName) {
        this.itemTypeName = itemTypeName;
    }

    public Set getBmsItems() {
        return this.bmsItems;
    }
    
    public void setBmsItems(Set bmsItems) {
        this.bmsItems = bmsItems;
    }
   








}
