package com.sinosoft.bms.entity;
// Generated 2009-5-19 11:36:47 by Hibernate Tools 3.1.0.beta4

import java.util.HashSet;
import java.util.Set;


/**
 * BmsItem generated by hbm2java
 */

public class BmsItem  implements java.io.Serializable {


    // Fields    

     private int itemId;
     private BmsItemCate bmsItemCate;
     private String itemCode;
     private String itemName;
     private String itemType;
     private Integer parentItem;
     private String subjCode;
     private String formula;
     private Set bmsTpRowDims = new HashSet(0);
     private Set bmsSheetItems = new HashSet(0);
     private Set bmsGsrowDims = new HashSet(0);
     private Set bmsControls = new HashSet(0);
     private Set bmsAlerts = new HashSet(0);


    // Constructors

    /** default constructor */
    public BmsItem() {
    }

	/** minimal constructor */
    public BmsItem(int itemId) {
        this.itemId = itemId;
    }
    
    /** full constructor */
    public BmsItem(int itemId, BmsItemCate bmsItemCate, String itemCode, String itemName, String itemType, Integer parentItem, String subjCode, String formula, Set bmsTpRowDims, Set bmsSheetItems, Set bmsGsrowDims, Set bmsControls, Set bmsAlerts) {
        this.itemId = itemId;
        this.bmsItemCate = bmsItemCate;
        this.itemCode = itemCode;
        this.itemName = itemName;
        this.itemType = itemType;
        this.parentItem = parentItem;
        this.subjCode = subjCode;
        this.formula = formula;
        this.bmsTpRowDims = bmsTpRowDims;
        this.bmsSheetItems = bmsSheetItems;
        this.bmsGsrowDims = bmsGsrowDims;
        this.bmsControls = bmsControls;
        this.bmsAlerts = bmsAlerts;
    }
    

   
    // Property accessors

    public int getItemId() {
        return this.itemId;
    }
    
    public void setItemId(int itemId) {
        this.itemId = itemId;
    }

    public BmsItemCate getBmsItemCate() {
        return this.bmsItemCate;
    }
    
    public void setBmsItemCate(BmsItemCate bmsItemCate) {
        this.bmsItemCate = bmsItemCate;
    }

    public String getItemCode() {
        return this.itemCode;
    }
    
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }

    public String getItemName() {
        return this.itemName;
    }
    
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    public String getItemType() {
        return this.itemType;
    }
    
    public void setItemType(String itemType) {
        this.itemType = itemType;
    }

    public Integer getParentItem() {
        return this.parentItem;
    }
    
    public void setParentItem(Integer parentItem) {
        this.parentItem = parentItem;
    }

    public String getSubjCode() {
        return this.subjCode;
    }
    
    public void setSubjCode(String subjCode) {
        this.subjCode = subjCode;
    }

    public String getFormula() {
        return this.formula;
    }
    
    public void setFormula(String formula) {
        this.formula = formula;
    }

    public Set getBmsTpRowDims() {
        return this.bmsTpRowDims;
    }
    
    public void setBmsTpRowDims(Set bmsTpRowDims) {
        this.bmsTpRowDims = bmsTpRowDims;
    }

    public Set getBmsSheetItems() {
        return this.bmsSheetItems;
    }
    
    public void setBmsSheetItems(Set bmsSheetItems) {
        this.bmsSheetItems = bmsSheetItems;
    }

    public Set getBmsGsrowDims() {
        return this.bmsGsrowDims;
    }
    
    public void setBmsGsrowDims(Set bmsGsrowDims) {
        this.bmsGsrowDims = bmsGsrowDims;
    }

    public Set getBmsControls() {
        return this.bmsControls;
    }
    
    public void setBmsControls(Set bmsControls) {
        this.bmsControls = bmsControls;
    }

    public Set getBmsAlerts() {
        return this.bmsAlerts;
    }
    
    public void setBmsAlerts(Set bmsAlerts) {
        this.bmsAlerts = bmsAlerts;
    }
   








}
