package com.sinosoft.bms.entity;
// Generated 2009-5-19 11:36:48 by Hibernate Tools 3.1.0.beta4

import java.util.HashSet;
import java.util.Set;


/**
 * BmsMenu generated by hbm2java
 */

public class BmsMenu  implements java.io.Serializable {


    // Fields    

     private int menuId;
     private String menuCode;
     private String menuName;
     private Integer parentMenu;
     private String script;
     private Character menuType;
     private Set bmsRcmenus = new HashSet(0);
     private Set bmsUserMenus = new HashSet(0);


    // Constructors

    /** default constructor */
    public BmsMenu() {
    }

	/** minimal constructor */
    public BmsMenu(int menuId) {
        this.menuId = menuId;
    }
    
    /** full constructor */
    public BmsMenu(int menuId, String menuCode, String menuName, Integer parentMenu, String script, Character menuType, Set bmsRcmenus, Set bmsUserMenus) {
        this.menuId = menuId;
        this.menuCode = menuCode;
        this.menuName = menuName;
        this.parentMenu = parentMenu;
        this.script = script;
        this.menuType = menuType;
        this.bmsRcmenus = bmsRcmenus;
        this.bmsUserMenus = bmsUserMenus;
    }
    

   
    // Property accessors

    public int getMenuId() {
        return this.menuId;
    }
    
    public void setMenuId(int menuId) {
        this.menuId = menuId;
    }

    public String getMenuCode() {
        return this.menuCode;
    }
    
    public void setMenuCode(String menuCode) {
        this.menuCode = menuCode;
    }

    public String getMenuName() {
        return this.menuName;
    }
    
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    public Integer getParentMenu() {
        return this.parentMenu;
    }
    
    public void setParentMenu(Integer parentMenu) {
        this.parentMenu = parentMenu;
    }

    public String getScript() {
        return this.script;
    }
    
    public void setScript(String script) {
        this.script = script;
    }

    public Character getMenuType() {
        return this.menuType;
    }
    
    public void setMenuType(Character menuType) {
        this.menuType = menuType;
    }

    public Set getBmsRcmenus() {
        return this.bmsRcmenus;
    }
    
    public void setBmsRcmenus(Set bmsRcmenus) {
        this.bmsRcmenus = bmsRcmenus;
    }

    public Set getBmsUserMenus() {
        return this.bmsUserMenus;
    }
    
    public void setBmsUserMenus(Set bmsUserMenus) {
        this.bmsUserMenus = bmsUserMenus;
    }
   








}
