package com.sinosoft.bms.entity;
// Generated 2009-5-19 11:36:47 by Hibernate Tools 3.1.0.beta4

import java.util.HashSet;
import java.util.Set;


/**
 * BmsObjectType generated by hbm2java
 */

public class BmsObjectType  implements java.io.Serializable {


    // Fields    

     private int bgObjTypeId;
     private String bjObjTypeCode;
     private String bjObjTypeName;
     private Set bmsObjects = new HashSet(0);


    // Constructors

    /** default constructor */
    public BmsObjectType() {
    }

	/** minimal constructor */
    public BmsObjectType(int bgObjTypeId) {
        this.bgObjTypeId = bgObjTypeId;
    }
    
    /** full constructor */
    public BmsObjectType(int bgObjTypeId, String bjObjTypeCode, String bjObjTypeName, Set bmsObjects) {
        this.bgObjTypeId = bgObjTypeId;
        this.bjObjTypeCode = bjObjTypeCode;
        this.bjObjTypeName = bjObjTypeName;
        this.bmsObjects = bmsObjects;
    }
    

   
    // Property accessors

    public int getBgObjTypeId() {
        return this.bgObjTypeId;
    }
    
    public void setBgObjTypeId(int bgObjTypeId) {
        this.bgObjTypeId = bgObjTypeId;
    }

    public String getBjObjTypeCode() {
        return this.bjObjTypeCode;
    }
    
    public void setBjObjTypeCode(String bjObjTypeCode) {
        this.bjObjTypeCode = bjObjTypeCode;
    }

    public String getBjObjTypeName() {
        return this.bjObjTypeName;
    }
    
    public void setBjObjTypeName(String bjObjTypeName) {
        this.bjObjTypeName = bjObjTypeName;
    }

    public Set getBmsObjects() {
        return this.bmsObjects;
    }
    
    public void setBmsObjects(Set bmsObjects) {
        this.bmsObjects = bmsObjects;
    }
   








}
