package com.sinosoft.bms.entity;
// Generated 2009-5-19 11:36:47 by Hibernate Tools 3.1.0.beta4



/**
 * BmsPeriod generated by hbm2java
 */

public class BmsPeriod  implements java.io.Serializable {


    // Fields    

     private BmsPeriodId id;
     private BmsPrdSch bmsPrdSch;


    // Constructors

    /** default constructor */
    public BmsPeriod() {
    }

	/** minimal constructor */
    public BmsPeriod(BmsPeriodId id) {
        this.id = id;
    }
    
    /** full constructor */
    public BmsPeriod(BmsPeriodId id, BmsPrdSch bmsPrdSch) {
        this.id = id;
        this.bmsPrdSch = bmsPrdSch;
    }
    

   
    // Property accessors

    public BmsPeriodId getId() {
        return this.id;
    }
    
    public void setId(BmsPeriodId id) {
        this.id = id;
    }

    public BmsPrdSch getBmsPrdSch() {
        return this.bmsPrdSch;
    }
    
    public void setBmsPrdSch(BmsPrdSch bmsPrdSch) {
        this.bmsPrdSch = bmsPrdSch;
    }
   








}
