package com.sinosoft.bms.entity;
// Generated 2009-5-19 11:36:47 by Hibernate Tools 3.1.0.beta4

import java.util.HashSet;
import java.util.Set;


/**
 * BmsPrdSch generated by hbm2java
 */

public class BmsPrdSch  implements java.io.Serializable {


    // Fields    

     private int prdSchId;
     private String prdSchCode;
     private String prdSchName;
     private Character yearFlag;
     private Character halfYearFlag;
     private Character quarterFlag;
     private Character monthFlag;
     private Character adjustFlag;
     private Set bmsPeriods = new HashSet(0);
     private Set bmsTemplets = new HashSet(0);


    // Constructors

    /** default constructor */
    public BmsPrdSch() {
    }

	/** minimal constructor */
    public BmsPrdSch(int prdSchId) {
        this.prdSchId = prdSchId;
    }
    
    /** full constructor */
    public BmsPrdSch(int prdSchId, String prdSchCode, String prdSchName, Character yearFlag, Character halfYearFlag, Character quarterFlag, Character monthFlag, Character adjustFlag, Set bmsPeriods, Set bmsTemplets) {
        this.prdSchId = prdSchId;
        this.prdSchCode = prdSchCode;
        this.prdSchName = prdSchName;
        this.yearFlag = yearFlag;
        this.halfYearFlag = halfYearFlag;
        this.quarterFlag = quarterFlag;
        this.monthFlag = monthFlag;
        this.adjustFlag = adjustFlag;
        this.bmsPeriods = bmsPeriods;
        this.bmsTemplets = bmsTemplets;
    }
    

   
    // Property accessors

    public int getPrdSchId() {
        return this.prdSchId;
    }
    
    public void setPrdSchId(int prdSchId) {
        this.prdSchId = prdSchId;
    }

    public String getPrdSchCode() {
        return this.prdSchCode;
    }
    
    public void setPrdSchCode(String prdSchCode) {
        this.prdSchCode = prdSchCode;
    }

    public String getPrdSchName() {
        return this.prdSchName;
    }
    
    public void setPrdSchName(String prdSchName) {
        this.prdSchName = prdSchName;
    }

    public Character getYearFlag() {
        return this.yearFlag;
    }
    
    public void setYearFlag(Character yearFlag) {
        this.yearFlag = yearFlag;
    }

    public Character getHalfYearFlag() {
        return this.halfYearFlag;
    }
    
    public void setHalfYearFlag(Character halfYearFlag) {
        this.halfYearFlag = halfYearFlag;
    }

    public Character getQuarterFlag() {
        return this.quarterFlag;
    }
    
    public void setQuarterFlag(Character quarterFlag) {
        this.quarterFlag = quarterFlag;
    }

    public Character getMonthFlag() {
        return this.monthFlag;
    }
    
    public void setMonthFlag(Character monthFlag) {
        this.monthFlag = monthFlag;
    }

    public Character getAdjustFlag() {
        return this.adjustFlag;
    }
    
    public void setAdjustFlag(Character adjustFlag) {
        this.adjustFlag = adjustFlag;
    }

    public Set getBmsPeriods() {
        return this.bmsPeriods;
    }
    
    public void setBmsPeriods(Set bmsPeriods) {
        this.bmsPeriods = bmsPeriods;
    }

    public Set getBmsTemplets() {
        return this.bmsTemplets;
    }
    
    public void setBmsTemplets(Set bmsTemplets) {
        this.bmsTemplets = bmsTemplets;
    }
   








}
