package com.sinosoft.bms.entity;
// Generated 2009-5-19 11:36:47 by Hibernate Tools 3.1.0.beta4



/**
 * BmsRcmenu generated by hbm2java
 */

public class BmsRcmenu  implements java.io.Serializable {


    // Fields    

     private BmsRcmenuId id;
     private BmsRoleClass bmsRoleClass;
     private BmsMenu bmsMenu;


    // Constructors

    /** default constructor */
    public BmsRcmenu() {
    }

	/** minimal constructor */
    public BmsRcmenu(BmsRcmenuId id) {
        this.id = id;
    }
    
    /** full constructor */
    public BmsRcmenu(BmsRcmenuId id, BmsRoleClass bmsRoleClass, BmsMenu bmsMenu) {
        this.id = id;
        this.bmsRoleClass = bmsRoleClass;
        this.bmsMenu = bmsMenu;
    }
    

   
    // Property accessors

    public BmsRcmenuId getId() {
        return this.id;
    }
    
    public void setId(BmsRcmenuId id) {
        this.id = id;
    }

    public BmsRoleClass getBmsRoleClass() {
        return this.bmsRoleClass;
    }
    
    public void setBmsRoleClass(BmsRoleClass bmsRoleClass) {
        this.bmsRoleClass = bmsRoleClass;
    }

    public BmsMenu getBmsMenu() {
        return this.bmsMenu;
    }
    
    public void setBmsMenu(BmsMenu bmsMenu) {
        this.bmsMenu = bmsMenu;
    }
   








}
