package com.sinosoft.bms.entity;
// Generated 2009-5-19 11:36:48 by Hibernate Tools 3.1.0.beta4



/**
 * BmsRcmenuId generated by hbm2java
 */

public class BmsRcmenuId  implements java.io.Serializable {


    // Fields    

     private Integer rcid;
     private Integer menuId;


    // Constructors

    /** default constructor */
    public BmsRcmenuId() {
    }

    
    /** full constructor */
    public BmsRcmenuId(Integer rcid, Integer menuId) {
        this.rcid = rcid;
        this.menuId = menuId;
    }
    

   
    // Property accessors

    public Integer getRcid() {
        return this.rcid;
    }
    
    public void setRcid(Integer rcid) {
        this.rcid = rcid;
    }

    public Integer getMenuId() {
        return this.menuId;
    }
    
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BmsRcmenuId) ) return false;
		 BmsRcmenuId castOther = ( BmsRcmenuId ) other; 
         
		 return ( (this.getRcid()==castOther.getRcid()) || ( this.getRcid()!=null && castOther.getRcid()!=null && this.getRcid().equals(castOther.getRcid()) ) )
 && ( (this.getMenuId()==castOther.getMenuId()) || ( this.getMenuId()!=null && castOther.getMenuId()!=null && this.getMenuId().equals(castOther.getMenuId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRcid() == null ? 0 : this.getRcid().hashCode() );
         result = 37 * result + ( getMenuId() == null ? 0 : this.getMenuId().hashCode() );
         return result;
   }   





}
