package com.sinosoft.bms.entity;
// Generated 2009-5-19 11:36:47 by Hibernate Tools 3.1.0.beta4

import java.util.HashSet;
import java.util.Set;


/**
 * BmsRoleClass generated by hbm2java
 */

public class BmsRoleClass  implements java.io.Serializable {


    // Fields    

     private int rcid;
     private String rccode;
     private String rcname;
     private Set bmsRcmenus = new HashSet(0);
     private Set bmsRoles = new HashSet(0);


    // Constructors

    /** default constructor */
    public BmsRoleClass() {
    }

	/** minimal constructor */
    public BmsRoleClass(int rcid) {
        this.rcid = rcid;
    }
    
    /** full constructor */
    public BmsRoleClass(int rcid, String rccode, String rcname, Set bmsRcmenus, Set bmsRoles) {
        this.rcid = rcid;
        this.rccode = rccode;
        this.rcname = rcname;
        this.bmsRcmenus = bmsRcmenus;
        this.bmsRoles = bmsRoles;
    }
    

   
    // Property accessors

    public int getRcid() {
        return this.rcid;
    }
    
    public void setRcid(int rcid) {
        this.rcid = rcid;
    }

    public String getRccode() {
        return this.rccode;
    }
    
    public void setRccode(String rccode) {
        this.rccode = rccode;
    }

    public String getRcname() {
        return this.rcname;
    }
    
    public void setRcname(String rcname) {
        this.rcname = rcname;
    }

    public Set getBmsRcmenus() {
        return this.bmsRcmenus;
    }
    
    public void setBmsRcmenus(Set bmsRcmenus) {
        this.bmsRcmenus = bmsRcmenus;
    }

    public Set getBmsRoles() {
        return this.bmsRoles;
    }
    
    public void setBmsRoles(Set bmsRoles) {
        this.bmsRoles = bmsRoles;
    }
   








}
