package com.sinosoft.bms.entity;
// Generated 2009-5-19 11:36:47 by Hibernate Tools 3.1.0.beta4

import java.util.HashSet;
import java.util.Set;


/**
 * BmsRole generated by hbm2java
 */

public class BmsRole  implements java.io.Serializable {


    // Fields    

     private int roleId;
     private BmsRoleClass bmsRoleClass;
     private BmsObject bmsObject;
     private String roleCode;
     private String roleName;
     private String useFlag;
     private Set bmsUserRoles = new HashSet(0);


    // Constructors

    /** default constructor */
    public BmsRole() {
    }

	/** minimal constructor */
    public BmsRole(int roleId) {
        this.roleId = roleId;
    }
    
    /** full constructor */
    public BmsRole(int roleId, BmsRoleClass bmsRoleClass, BmsObject bmsObject, String roleCode, String roleName, String useFlag, Set bmsUserRoles) {
        this.roleId = roleId;
        this.bmsRoleClass = bmsRoleClass;
        this.bmsObject = bmsObject;
        this.roleCode = roleCode;
        this.roleName = roleName;
        this.useFlag = useFlag;
        this.bmsUserRoles = bmsUserRoles;
    }
    

   
    // Property accessors

    public int getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }

    public BmsRoleClass getBmsRoleClass() {
        return this.bmsRoleClass;
    }
    
    public void setBmsRoleClass(BmsRoleClass bmsRoleClass) {
        this.bmsRoleClass = bmsRoleClass;
    }

    public BmsObject getBmsObject() {
        return this.bmsObject;
    }
    
    public void setBmsObject(BmsObject bmsObject) {
        this.bmsObject = bmsObject;
    }

    public String getRoleCode() {
        return this.roleCode;
    }
    
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode;
    }

    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    public String getUseFlag() {
        return this.useFlag;
    }
    
    public void setUseFlag(String useFlag) {
        this.useFlag = useFlag;
    }

    public Set getBmsUserRoles() {
        return this.bmsUserRoles;
    }
    
    public void setBmsUserRoles(Set bmsUserRoles) {
        this.bmsUserRoles = bmsUserRoles;
    }
   








}
