package com.sinosoft.bms.entity;
// Generated 2009-5-19 11:36:48 by Hibernate Tools 3.1.0.beta4

import java.util.HashSet;
import java.util.Set;


/**
 * BmsSheet generated by hbm2java
 */

public class BmsSheet  implements java.io.Serializable {


    // Fields    

     private int sheetId;
     private BmsTpParamDim bmsTpParamDim;
     private BmsTemplet bmsTemplet;
     private BmsObject bmsObject;
     private String sheetCode;
     private String sheetTitle;
     private Integer addUser;
     private String addDate;
     private Integer apprUser;
     private String apprDate;
     private Integer gatherUser;
     private String gatherDate;
     private String repDate;
     private Character apprFlag;
     private Character gatheredFlag;
     private Character repFlag;
     private Character enabledFlag;
     private String apprAdvice;
     private Character isGatherSheet;
     private Character colGatherMethod;
     private Set bmsGsparamDims = new HashSet(0);
     private Set bmsGsrowDims = new HashSet(0);
     private Set bmsGschildrens = new HashSet(0);
     private Set bmsSheetItems = new HashSet(0);


    // Constructors

    /** default constructor */
    public BmsSheet() {
    }

	/** minimal constructor */
    public BmsSheet(int sheetId) {
        this.sheetId = sheetId;
    }
    
    /** full constructor */
    public BmsSheet(int sheetId, BmsTpParamDim bmsTpParamDim, BmsTemplet bmsTemplet, BmsObject bmsObject, String sheetCode, String sheetTitle, Integer addUser, String addDate, Integer apprUser, String apprDate, Integer gatherUser, String gatherDate, String repDate, Character apprFlag, Character gatheredFlag, Character repFlag, Character enabledFlag, String apprAdvice, Character isGatherSheet, Character colGatherMethod, Set bmsGsparamDims, Set bmsGsrowDims, Set bmsGschildrens, Set bmsSheetItems) {
        this.sheetId = sheetId;
        this.bmsTpParamDim = bmsTpParamDim;
        this.bmsTemplet = bmsTemplet;
        this.bmsObject = bmsObject;
        this.sheetCode = sheetCode;
        this.sheetTitle = sheetTitle;
        this.addUser = addUser;
        this.addDate = addDate;
        this.apprUser = apprUser;
        this.apprDate = apprDate;
        this.gatherUser = gatherUser;
        this.gatherDate = gatherDate;
        this.repDate = repDate;
        this.apprFlag = apprFlag;
        this.gatheredFlag = gatheredFlag;
        this.repFlag = repFlag;
        this.enabledFlag = enabledFlag;
        this.apprAdvice = apprAdvice;
        this.isGatherSheet = isGatherSheet;
        this.colGatherMethod = colGatherMethod;
        this.bmsGsparamDims = bmsGsparamDims;
        this.bmsGsrowDims = bmsGsrowDims;
        this.bmsGschildrens = bmsGschildrens;
        this.bmsSheetItems = bmsSheetItems;
    }
    

   
    // Property accessors

    public int getSheetId() {
        return this.sheetId;
    }
    
    public void setSheetId(int sheetId) {
        this.sheetId = sheetId;
    }

    public BmsTpParamDim getBmsTpParamDim() {
        return this.bmsTpParamDim;
    }
    
    public void setBmsTpParamDim(BmsTpParamDim bmsTpParamDim) {
        this.bmsTpParamDim = bmsTpParamDim;
    }

    public BmsTemplet getBmsTemplet() {
        return this.bmsTemplet;
    }
    
    public void setBmsTemplet(BmsTemplet bmsTemplet) {
        this.bmsTemplet = bmsTemplet;
    }

    public BmsObject getBmsObject() {
        return this.bmsObject;
    }
    
    public void setBmsObject(BmsObject bmsObject) {
        this.bmsObject = bmsObject;
    }

    public String getSheetCode() {
        return this.sheetCode;
    }
    
    public void setSheetCode(String sheetCode) {
        this.sheetCode = sheetCode;
    }

    public String getSheetTitle() {
        return this.sheetTitle;
    }
    
    public void setSheetTitle(String sheetTitle) {
        this.sheetTitle = sheetTitle;
    }

    public Integer getAddUser() {
        return this.addUser;
    }
    
    public void setAddUser(Integer addUser) {
        this.addUser = addUser;
    }

    public String getAddDate() {
        return this.addDate;
    }
    
    public void setAddDate(String addDate) {
        this.addDate = addDate;
    }

    public Integer getApprUser() {
        return this.apprUser;
    }
    
    public void setApprUser(Integer apprUser) {
        this.apprUser = apprUser;
    }

    public String getApprDate() {
        return this.apprDate;
    }
    
    public void setApprDate(String apprDate) {
        this.apprDate = apprDate;
    }

    public Integer getGatherUser() {
        return this.gatherUser;
    }
    
    public void setGatherUser(Integer gatherUser) {
        this.gatherUser = gatherUser;
    }

    public String getGatherDate() {
        return this.gatherDate;
    }
    
    public void setGatherDate(String gatherDate) {
        this.gatherDate = gatherDate;
    }

    public String getRepDate() {
        return this.repDate;
    }
    
    public void setRepDate(String repDate) {
        this.repDate = repDate;
    }

    public Character getApprFlag() {
        return this.apprFlag;
    }
    
    public void setApprFlag(Character apprFlag) {
        this.apprFlag = apprFlag;
    }

    public Character getGatheredFlag() {
        return this.gatheredFlag;
    }
    
    public void setGatheredFlag(Character gatheredFlag) {
        this.gatheredFlag = gatheredFlag;
    }

    public Character getRepFlag() {
        return this.repFlag;
    }
    
    public void setRepFlag(Character repFlag) {
        this.repFlag = repFlag;
    }

    public Character getEnabledFlag() {
        return this.enabledFlag;
    }
    
    public void setEnabledFlag(Character enabledFlag) {
        this.enabledFlag = enabledFlag;
    }

    public String getApprAdvice() {
        return this.apprAdvice;
    }
    
    public void setApprAdvice(String apprAdvice) {
        this.apprAdvice = apprAdvice;
    }

    public Character getIsGatherSheet() {
        return this.isGatherSheet;
    }
    
    public void setIsGatherSheet(Character isGatherSheet) {
        this.isGatherSheet = isGatherSheet;
    }

    public Character getColGatherMethod() {
        return this.colGatherMethod;
    }
    
    public void setColGatherMethod(Character colGatherMethod) {
        this.colGatherMethod = colGatherMethod;
    }

    public Set getBmsGsparamDims() {
        return this.bmsGsparamDims;
    }
    
    public void setBmsGsparamDims(Set bmsGsparamDims) {
        this.bmsGsparamDims = bmsGsparamDims;
    }

    public Set getBmsGsrowDims() {
        return this.bmsGsrowDims;
    }
    
    public void setBmsGsrowDims(Set bmsGsrowDims) {
        this.bmsGsrowDims = bmsGsrowDims;
    }

    public Set getBmsGschildrens() {
        return this.bmsGschildrens;
    }
    
    public void setBmsGschildrens(Set bmsGschildrens) {
        this.bmsGschildrens = bmsGschildrens;
    }

    public Set getBmsSheetItems() {
        return this.bmsSheetItems;
    }
    
    public void setBmsSheetItems(Set bmsSheetItems) {
        this.bmsSheetItems = bmsSheetItems;
    }
   








}
