package com.sinosoft.bms.entity;
// Generated 2009-5-19 11:36:47 by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;


/**
 * BmsSheetItem generated by hbm2java
 */

public class BmsSheetItem  implements java.io.Serializable {


    // Fields    

     private int sheetItemId;
     private BmsTpBgObj bmsTpBgObj;
     private BmsItem bmsItem;
     private BmsTemplet bmsTemplet;
     private BmsTpColDim bmsTpColDim;
     private BmsSheet bmsSheet;
     private BmsObject bmsObject;
     private BmsTpRowDim bmsTpRowDim;
     private BigDecimal itemVal;
     private Character planValFlag;
     private Character byFormulaFlag;


    // Constructors

    /** default constructor */
    public BmsSheetItem() {
    }

	/** minimal constructor */
    public BmsSheetItem(int sheetItemId) {
        this.sheetItemId = sheetItemId;
    }
    
    /** full constructor */
    public BmsSheetItem(int sheetItemId, BmsTpBgObj bmsTpBgObj, BmsItem bmsItem, BmsTemplet bmsTemplet, BmsTpColDim bmsTpColDim, BmsSheet bmsSheet, BmsObject bmsObject, BmsTpRowDim bmsTpRowDim, BigDecimal itemVal, Character planValFlag, Character byFormulaFlag) {
        this.sheetItemId = sheetItemId;
        this.bmsTpBgObj = bmsTpBgObj;
        this.bmsItem = bmsItem;
        this.bmsTemplet = bmsTemplet;
        this.bmsTpColDim = bmsTpColDim;
        this.bmsSheet = bmsSheet;
        this.bmsObject = bmsObject;
        this.bmsTpRowDim = bmsTpRowDim;
        this.itemVal = itemVal;
        this.planValFlag = planValFlag;
        this.byFormulaFlag = byFormulaFlag;
    }
    

   
    // Property accessors

    public int getSheetItemId() {
        return this.sheetItemId;
    }
    
    public void setSheetItemId(int sheetItemId) {
        this.sheetItemId = sheetItemId;
    }

    public BmsTpBgObj getBmsTpBgObj() {
        return this.bmsTpBgObj;
    }
    
    public void setBmsTpBgObj(BmsTpBgObj bmsTpBgObj) {
        this.bmsTpBgObj = bmsTpBgObj;
    }

    public BmsItem getBmsItem() {
        return this.bmsItem;
    }
    
    public void setBmsItem(BmsItem bmsItem) {
        this.bmsItem = bmsItem;
    }

    public BmsTemplet getBmsTemplet() {
        return this.bmsTemplet;
    }
    
    public void setBmsTemplet(BmsTemplet bmsTemplet) {
        this.bmsTemplet = bmsTemplet;
    }

    public BmsTpColDim getBmsTpColDim() {
        return this.bmsTpColDim;
    }
    
    public void setBmsTpColDim(BmsTpColDim bmsTpColDim) {
        this.bmsTpColDim = bmsTpColDim;
    }

    public BmsSheet getBmsSheet() {
        return this.bmsSheet;
    }
    
    public void setBmsSheet(BmsSheet bmsSheet) {
        this.bmsSheet = bmsSheet;
    }

    public BmsObject getBmsObject() {
        return this.bmsObject;
    }
    
    public void setBmsObject(BmsObject bmsObject) {
        this.bmsObject = bmsObject;
    }

    public BmsTpRowDim getBmsTpRowDim() {
        return this.bmsTpRowDim;
    }
    
    public void setBmsTpRowDim(BmsTpRowDim bmsTpRowDim) {
        this.bmsTpRowDim = bmsTpRowDim;
    }

    public BigDecimal getItemVal() {
        return this.itemVal;
    }
    
    public void setItemVal(BigDecimal itemVal) {
        this.itemVal = itemVal;
    }

    public Character getPlanValFlag() {
        return this.planValFlag;
    }
    
    public void setPlanValFlag(Character planValFlag) {
        this.planValFlag = planValFlag;
    }

    public Character getByFormulaFlag() {
        return this.byFormulaFlag;
    }
    
    public void setByFormulaFlag(Character byFormulaFlag) {
        this.byFormulaFlag = byFormulaFlag;
    }
   








}
