package com.sinosoft.bms.entity;
// Generated 2009-5-19 11:36:47 by Hibernate Tools 3.1.0.beta4

import java.util.HashSet;
import java.util.Set;


/**
 * BmsTpBgObj generated by hbm2java
 */

public class BmsTpBgObj  implements java.io.Serializable {


    // Fields    

     private int tpBgObjId;
     private BmsTemplet bmsTemplet;
     private BmsObject bmsObject;
     private Character leafFlag;
     private Set bmsSheetItems = new HashSet(0);


    // Constructors

    /** default constructor */
    public BmsTpBgObj() {
    }

	/** minimal constructor */
    public BmsTpBgObj(int tpBgObjId) {
        this.tpBgObjId = tpBgObjId;
    }
    
    /** full constructor */
    public BmsTpBgObj(int tpBgObjId, BmsTemplet bmsTemplet, BmsObject bmsObject, Character leafFlag, Set bmsSheetItems) {
        this.tpBgObjId = tpBgObjId;
        this.bmsTemplet = bmsTemplet;
        this.bmsObject = bmsObject;
        this.leafFlag = leafFlag;
        this.bmsSheetItems = bmsSheetItems;
    }
    

   
    // Property accessors

    public int getTpBgObjId() {
        return this.tpBgObjId;
    }
    
    public void setTpBgObjId(int tpBgObjId) {
        this.tpBgObjId = tpBgObjId;
    }

    public BmsTemplet getBmsTemplet() {
        return this.bmsTemplet;
    }
    
    public void setBmsTemplet(BmsTemplet bmsTemplet) {
        this.bmsTemplet = bmsTemplet;
    }

    public BmsObject getBmsObject() {
        return this.bmsObject;
    }
    
    public void setBmsObject(BmsObject bmsObject) {
        this.bmsObject = bmsObject;
    }

    public Character getLeafFlag() {
        return this.leafFlag;
    }
    
    public void setLeafFlag(Character leafFlag) {
        this.leafFlag = leafFlag;
    }

    public Set getBmsSheetItems() {
        return this.bmsSheetItems;
    }
    
    public void setBmsSheetItems(Set bmsSheetItems) {
        this.bmsSheetItems = bmsSheetItems;
    }
   








}
