package com.sinosoft.bms.entity;
// Generated 2009-5-19 11:36:47 by Hibernate Tools 3.1.0.beta4

import java.util.HashSet;
import java.util.Set;


/**
 * BmsTemplet generated by hbm2java
 */

public class BmsTemplet  implements java.io.Serializable {


    // Fields    

     private int tpId;
     private BmsScheme bmsScheme;
     private BmsPrdSch bmsPrdSch;
     private String tpCode;
     private String tpName;
     private Character useFlag;
     private Character disFlag;
     private Integer inputRoleId;
     private Integer apprRoleId;
     private Integer enableRoleId;
     private Character tpType;
     private Integer dataStartRow;
     private Integer dataStartCol;
     private Integer dataEndRow;
     private Integer dataEndCol;
     private Set bmsTpRowDims = new HashSet(0);
     private Set bmsTpColDims = new HashSet(0);
     private Set bmsTpBgObjs = new HashSet(0);
     private Set bmsSheets = new HashSet(0);
     private Set bmsTempletAttachs = new HashSet(0);
     private Set bmsTpParamDims = new HashSet(0);
     private Set bmsSheetItems = new HashSet(0);


    // Constructors

    /** default constructor */
    public BmsTemplet() {
    }

	/** minimal constructor */
    public BmsTemplet(int tpId) {
        this.tpId = tpId;
    }
    
    /** full constructor */
    public BmsTemplet(int tpId, BmsScheme bmsScheme, BmsPrdSch bmsPrdSch, String tpCode, String tpName, Character useFlag, Character disFlag, Integer inputRoleId, Integer apprRoleId, Integer enableRoleId, Character tpType, Integer dataStartRow, Integer dataStartCol, Integer dataEndRow, Integer dataEndCol, Set bmsTpRowDims, Set bmsTpColDims, Set bmsTpBgObjs, Set bmsSheets, Set bmsTempletAttachs, Set bmsTpParamDims, Set bmsSheetItems) {
        this.tpId = tpId;
        this.bmsScheme = bmsScheme;
        this.bmsPrdSch = bmsPrdSch;
        this.tpCode = tpCode;
        this.tpName = tpName;
        this.useFlag = useFlag;
        this.disFlag = disFlag;
        this.inputRoleId = inputRoleId;
        this.apprRoleId = apprRoleId;
        this.enableRoleId = enableRoleId;
        this.tpType = tpType;
        this.dataStartRow = dataStartRow;
        this.dataStartCol = dataStartCol;
        this.dataEndRow = dataEndRow;
        this.dataEndCol = dataEndCol;
        this.bmsTpRowDims = bmsTpRowDims;
        this.bmsTpColDims = bmsTpColDims;
        this.bmsTpBgObjs = bmsTpBgObjs;
        this.bmsSheets = bmsSheets;
        this.bmsTempletAttachs = bmsTempletAttachs;
        this.bmsTpParamDims = bmsTpParamDims;
        this.bmsSheetItems = bmsSheetItems;
    }
    

   
    // Property accessors

    public int getTpId() {
        return this.tpId;
    }
    
    public void setTpId(int tpId) {
        this.tpId = tpId;
    }

    public BmsScheme getBmsScheme() {
        return this.bmsScheme;
    }
    
    public void setBmsScheme(BmsScheme bmsScheme) {
        this.bmsScheme = bmsScheme;
    }

    public BmsPrdSch getBmsPrdSch() {
        return this.bmsPrdSch;
    }
    
    public void setBmsPrdSch(BmsPrdSch bmsPrdSch) {
        this.bmsPrdSch = bmsPrdSch;
    }

    public String getTpCode() {
        return this.tpCode;
    }
    
    public void setTpCode(String tpCode) {
        this.tpCode = tpCode;
    }

    public String getTpName() {
        return this.tpName;
    }
    
    public void setTpName(String tpName) {
        this.tpName = tpName;
    }

    public Character getUseFlag() {
        return this.useFlag;
    }
    
    public void setUseFlag(Character useFlag) {
        this.useFlag = useFlag;
    }

    public Character getDisFlag() {
        return this.disFlag;
    }
    
    public void setDisFlag(Character disFlag) {
        this.disFlag = disFlag;
    }

    public Integer getInputRoleId() {
        return this.inputRoleId;
    }
    
    public void setInputRoleId(Integer inputRoleId) {
        this.inputRoleId = inputRoleId;
    }

    public Integer getApprRoleId() {
        return this.apprRoleId;
    }
    
    public void setApprRoleId(Integer apprRoleId) {
        this.apprRoleId = apprRoleId;
    }

    public Integer getEnableRoleId() {
        return this.enableRoleId;
    }
    
    public void setEnableRoleId(Integer enableRoleId) {
        this.enableRoleId = enableRoleId;
    }

    public Character getTpType() {
        return this.tpType;
    }
    
    public void setTpType(Character tpType) {
        this.tpType = tpType;
    }

    public Integer getDataStartRow() {
        return this.dataStartRow;
    }
    
    public void setDataStartRow(Integer dataStartRow) {
        this.dataStartRow = dataStartRow;
    }

    public Integer getDataStartCol() {
        return this.dataStartCol;
    }
    
    public void setDataStartCol(Integer dataStartCol) {
        this.dataStartCol = dataStartCol;
    }

    public Integer getDataEndRow() {
        return this.dataEndRow;
    }
    
    public void setDataEndRow(Integer dataEndRow) {
        this.dataEndRow = dataEndRow;
    }

    public Integer getDataEndCol() {
        return this.dataEndCol;
    }
    
    public void setDataEndCol(Integer dataEndCol) {
        this.dataEndCol = dataEndCol;
    }

    public Set getBmsTpRowDims() {
        return this.bmsTpRowDims;
    }
    
    public void setBmsTpRowDims(Set bmsTpRowDims) {
        this.bmsTpRowDims = bmsTpRowDims;
    }

    public Set getBmsTpColDims() {
        return this.bmsTpColDims;
    }
    
    public void setBmsTpColDims(Set bmsTpColDims) {
        this.bmsTpColDims = bmsTpColDims;
    }

    public Set getBmsTpBgObjs() {
        return this.bmsTpBgObjs;
    }
    
    public void setBmsTpBgObjs(Set bmsTpBgObjs) {
        this.bmsTpBgObjs = bmsTpBgObjs;
    }

    public Set getBmsSheets() {
        return this.bmsSheets;
    }
    
    public void setBmsSheets(Set bmsSheets) {
        this.bmsSheets = bmsSheets;
    }

    public Set getBmsTempletAttachs() {
        return this.bmsTempletAttachs;
    }
    
    public void setBmsTempletAttachs(Set bmsTempletAttachs) {
        this.bmsTempletAttachs = bmsTempletAttachs;
    }

    public Set getBmsTpParamDims() {
        return this.bmsTpParamDims;
    }
    
    public void setBmsTpParamDims(Set bmsTpParamDims) {
        this.bmsTpParamDims = bmsTpParamDims;
    }

    public Set getBmsSheetItems() {
        return this.bmsSheetItems;
    }
    
    public void setBmsSheetItems(Set bmsSheetItems) {
        this.bmsSheetItems = bmsSheetItems;
    }
   








}
