package com.sinosoft.bms.entity;
// Generated 2009-5-19 11:36:48 by Hibernate Tools 3.1.0.beta4

import java.util.HashSet;
import java.util.Set;


/**
 * BmsTpColDim generated by hbm2java
 */

public class BmsTpColDim  implements java.io.Serializable {


    // Fields    

     private int tpColDimId;
     private BmsTemplet bmsTemplet;
     private String colCode;
     private String colName;
     private Integer parentCol;
     private Integer colType;
     private String formula;
     private Set bmsSheetItems = new HashSet(0);


    // Constructors

    /** default constructor */
    public BmsTpColDim() {
    }

	/** minimal constructor */
    public BmsTpColDim(int tpColDimId) {
        this.tpColDimId = tpColDimId;
    }
    
    /** full constructor */
    public BmsTpColDim(int tpColDimId, BmsTemplet bmsTemplet, String colCode, String colName, Integer parentCol, Integer colType, String formula, Set bmsSheetItems) {
        this.tpColDimId = tpColDimId;
        this.bmsTemplet = bmsTemplet;
        this.colCode = colCode;
        this.colName = colName;
        this.parentCol = parentCol;
        this.colType = colType;
        this.formula = formula;
        this.bmsSheetItems = bmsSheetItems;
    }
    

   
    // Property accessors

    public int getTpColDimId() {
        return this.tpColDimId;
    }
    
    public void setTpColDimId(int tpColDimId) {
        this.tpColDimId = tpColDimId;
    }

    public BmsTemplet getBmsTemplet() {
        return this.bmsTemplet;
    }
    
    public void setBmsTemplet(BmsTemplet bmsTemplet) {
        this.bmsTemplet = bmsTemplet;
    }

    public String getColCode() {
        return this.colCode;
    }
    
    public void setColCode(String colCode) {
        this.colCode = colCode;
    }

    public String getColName() {
        return this.colName;
    }
    
    public void setColName(String colName) {
        this.colName = colName;
    }

    public Integer getParentCol() {
        return this.parentCol;
    }
    
    public void setParentCol(Integer parentCol) {
        this.parentCol = parentCol;
    }

    public Integer getColType() {
        return this.colType;
    }
    
    public void setColType(Integer colType) {
        this.colType = colType;
    }

    public String getFormula() {
        return this.formula;
    }
    
    public void setFormula(String formula) {
        this.formula = formula;
    }

    public Set getBmsSheetItems() {
        return this.bmsSheetItems;
    }
    
    public void setBmsSheetItems(Set bmsSheetItems) {
        this.bmsSheetItems = bmsSheetItems;
    }
   








}
