package com.sinosoft.bms.entity;
// Generated 2009-5-19 11:36:47 by Hibernate Tools 3.1.0.beta4

import java.util.HashSet;
import java.util.Set;


/**
 * BmsUser generated by hbm2java
 */

public class BmsUser  implements java.io.Serializable {


    // Fields    

     private int userId;
     private BmsObject bmsObject;
     private String userCode;
     private String userName;
     private String passWord;
     private Character useFlag;
     private String email;
     private String phone;
     private Set bmsUserRoles = new HashSet(0);
     private Set bmsUserMenus = new HashSet(0);
     private Set bmsUserBgObjs = new HashSet(0);


    // Constructors

    /** default constructor */
    public BmsUser() {
    }

	/** minimal constructor */
    public BmsUser(int userId) {
        this.userId = userId;
    }
    
    /** full constructor */
    public BmsUser(int userId, BmsObject bmsObject, String userCode, String userName, String passWord, Character useFlag, String email, String phone, Set bmsUserRoles, Set bmsUserMenus, Set bmsUserBgObjs) {
        this.userId = userId;
        this.bmsObject = bmsObject;
        this.userCode = userCode;
        this.userName = userName;
        this.passWord = passWord;
        this.useFlag = useFlag;
        this.email = email;
        this.phone = phone;
        this.bmsUserRoles = bmsUserRoles;
        this.bmsUserMenus = bmsUserMenus;
        this.bmsUserBgObjs = bmsUserBgObjs;
    }
    

   
    // Property accessors

    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }

    public BmsObject getBmsObject() {
        return this.bmsObject;
    }
    
    public void setBmsObject(BmsObject bmsObject) {
        this.bmsObject = bmsObject;
    }

    public String getUserCode() {
        return this.userCode;
    }
    
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassWord() {
        return this.passWord;
    }
    
    public void setPassWord(String passWord) {
        this.passWord = passWord;
    }

    public Character getUseFlag() {
        return this.useFlag;
    }
    
    public void setUseFlag(Character useFlag) {
        this.useFlag = useFlag;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    public Set getBmsUserRoles() {
        return this.bmsUserRoles;
    }
    
    public void setBmsUserRoles(Set bmsUserRoles) {
        this.bmsUserRoles = bmsUserRoles;
    }

    public Set getBmsUserMenus() {
        return this.bmsUserMenus;
    }
    
    public void setBmsUserMenus(Set bmsUserMenus) {
        this.bmsUserMenus = bmsUserMenus;
    }

    public Set getBmsUserBgObjs() {
        return this.bmsUserBgObjs;
    }
    
    public void setBmsUserBgObjs(Set bmsUserBgObjs) {
        this.bmsUserBgObjs = bmsUserBgObjs;
    }
   








}
