package com.sinosoft.bms.entity;
// Generated 2009-5-19 11:36:48 by Hibernate Tools 3.1.0.beta4



/**
 * BmsUserMenuId generated by hbm2java
 */

public class BmsUserMenuId  implements java.io.Serializable {


    // Fields    

     private Integer userId;
     private Integer menuId;


    // Constructors

    /** default constructor */
    public BmsUserMenuId() {
    }

    
    /** full constructor */
    public BmsUserMenuId(Integer userId, Integer menuId) {
        this.userId = userId;
        this.menuId = menuId;
    }
    

   
    // Property accessors

    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getMenuId() {
        return this.menuId;
    }
    
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BmsUserMenuId) ) return false;
		 BmsUserMenuId castOther = ( BmsUserMenuId ) other; 
         
		 return ( (this.getUserId()==castOther.getUserId()) || ( this.getUserId()!=null && castOther.getUserId()!=null && this.getUserId().equals(castOther.getUserId()) ) )
 && ( (this.getMenuId()==castOther.getMenuId()) || ( this.getMenuId()!=null && castOther.getMenuId()!=null && this.getMenuId().equals(castOther.getMenuId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUserId() == null ? 0 : this.getUserId().hashCode() );
         result = 37 * result + ( getMenuId() == null ? 0 : this.getMenuId().hashCode() );
         return result;
   }   





}
