package com.sinosoft.bms.entity;
// Generated 2009-5-19 11:36:47 by Hibernate Tools 3.1.0.beta4



/**
 * BmsUserBgObj generated by hbm2java
 */

public class BmsUserBgObj  implements java.io.Serializable {


    // Fields    

     private BmsUserBgObjId id;
     private BmsUser bmsUser;
     private BmsObject bmsObject;


    // Constructors

    /** default constructor */
    public BmsUserBgObj() {
    }

	/** minimal constructor */
    public BmsUserBgObj(BmsUserBgObjId id) {
        this.id = id;
    }
    
    /** full constructor */
    public BmsUserBgObj(BmsUserBgObjId id, BmsUser bmsUser, BmsObject bmsObject) {
        this.id = id;
        this.bmsUser = bmsUser;
        this.bmsObject = bmsObject;
    }
    

   
    // Property accessors

    public BmsUserBgObjId getId() {
        return this.id;
    }
    
    public void setId(BmsUserBgObjId id) {
        this.id = id;
    }

    public BmsUser getBmsUser() {
        return this.bmsUser;
    }
    
    public void setBmsUser(BmsUser bmsUser) {
        this.bmsUser = bmsUser;
    }

    public BmsObject getBmsObject() {
        return this.bmsObject;
    }
    
    public void setBmsObject(BmsObject bmsObject) {
        this.bmsObject = bmsObject;
    }
   








}
