package com.sinosoft.bms.entity;
// Generated 2009-5-19 11:36:47 by Hibernate Tools 3.1.0.beta4



/**
 * BmsUserRole generated by hbm2java
 */

public class BmsUserRole  implements java.io.Serializable {


    // Fields    

     private BmsUserRoleId id;
     private BmsUser bmsUser;
     private BmsRole bmsRole;


    // Constructors

    /** default constructor */
    public BmsUserRole() {
    }

	/** minimal constructor */
    public BmsUserRole(BmsUserRoleId id) {
        this.id = id;
    }
    
    /** full constructor */
    public BmsUserRole(BmsUserRoleId id, BmsUser bmsUser, BmsRole bmsRole) {
        this.id = id;
        this.bmsUser = bmsUser;
        this.bmsRole = bmsRole;
    }
    

   
    // Property accessors

    public BmsUserRoleId getId() {
        return this.id;
    }
    
    public void setId(BmsUserRoleId id) {
        this.id = id;
    }

    public BmsUser getBmsUser() {
        return this.bmsUser;
    }
    
    public void setBmsUser(BmsUser bmsUser) {
        this.bmsUser = bmsUser;
    }

    public BmsRole getBmsRole() {
        return this.bmsRole;
    }
    
    public void setBmsRole(BmsRole bmsRole) {
        this.bmsRole = bmsRole;
    }
   








}
