package com.sinosoft.bms.entity;
// Generated 2009-5-19 11:36:48 by Hibernate Tools 3.1.0.beta4



/**
 * BmsUserBgObjId generated by hbm2java
 */

public class BmsUserBgObjId  implements java.io.Serializable {


    // Fields    

     private Integer userId;
     private Integer bgObjId;


    // Constructors

    /** default constructor */
    public BmsUserBgObjId() {
    }

    
    /** full constructor */
    public BmsUserBgObjId(Integer userId, Integer bgObjId) {
        this.userId = userId;
        this.bgObjId = bgObjId;
    }
    

   
    // Property accessors

    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getBgObjId() {
        return this.bgObjId;
    }
    
    public void setBgObjId(Integer bgObjId) {
        this.bgObjId = bgObjId;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BmsUserBgObjId) ) return false;
		 BmsUserBgObjId castOther = ( BmsUserBgObjId ) other; 
         
		 return ( (this.getUserId()==castOther.getUserId()) || ( this.getUserId()!=null && castOther.getUserId()!=null && this.getUserId().equals(castOther.getUserId()) ) )
 && ( (this.getBgObjId()==castOther.getBgObjId()) || ( this.getBgObjId()!=null && castOther.getBgObjId()!=null && this.getBgObjId().equals(castOther.getBgObjId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUserId() == null ? 0 : this.getUserId().hashCode() );
         result = 37 * result + ( getBgObjId() == null ? 0 : this.getBgObjId().hashCode() );
         return result;
   }   





}
